export const WEB3_INJECTED = 'WEB3_INJECTED';
export const WEB3_CREATED = 'WEB3_CREATED';
export const CHANGED_METAMASK_CREDENTIALS = 'CHANGED_METAMASK_CREDENTIALS';
export const TRANSACTION_ATTEMPT = 'TRANSACTION_ATTEMPT';
export const TRANSACTION_SUBMITTED = 'TRANSACTION_SUBMITTED';
export const TRANSACTION_DENIED = 'TRANSACTION_DENIED';
export const TRANSACTION_FAILUR = 'TRANSACTION_FAILUR';
